name: Teste de Build e Testes em Múltiplas Plataformas

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-e-test:
        name: Build e Testes

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.8", "3.11"]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Configurar Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Instalar dependências
              run: |
                  python -m pip install --upgrade pip

            - name: Executar testes
              run: python -m unittest test_imc.py
